
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: weather-db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Express Backend
  server:
    build:
      context: ./server
    container_name: weather-api
    depends_on:
      - postgres
    environment:
      PGHOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
      PGDATABASE: ${DB_NAME}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped

  # Vue Frontend
  client:
    build:
      context: ./client
    container_name: weather-ui
    depends_on:
      - server
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  postgres_data:
