# version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: weather-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Express Backend
  server:
    build:
      context: ./server
    container_name: weather-api
    depends_on:
      - postgres
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=weather_app
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Vue Frontend
  client:
    build:
      context: ./client
    container_name: weather-ui
    depends_on:
      - server
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  postgres_data:
