version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
